apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
   app: ds-app
spec:
  selector:
    matchLabels: 
     app: ds-app
  template:
    metadata:
     labels:
      app: ds-app
    spec:
      containers:
        - name: elasticsearch
          image: k8s.gcr.io/fluentd-elasticsearch:1.20