apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:
    name: lbl-pod
    env: dev
spec:
  containers:
  - name: lbl-pod-name
    image: arun161087/webserver-http
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
