apiVersion: v1
kind: Pod
metadata:
  name: arunapp
  labels:
    name: arunapp
    app: arunapp
spec:
  containers:
  - name: arunapp
    image: arun161087/webserver-http
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
