apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: dev
  name: bee
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: bee
  tolerations:
  - key: "spray"
    operator: "Equal"
    value: "mortein"
    effect: "NoSchedule"